apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsconfig-injector-webhook-configmap
  namespace: kube-system
data:
  dnsconfig.yaml: |
    options:
    - name: ndots
      value: "1"
    searches:
    - svc.cluster.local
